
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: 127.0.0.1

development:
  <<: *default
  database: splurty_development


test:
  <<: *default
  database: splurty_test


production:
  <<: *default
  database: splurty_production
